site_name: PBR Painter
nav:
   - index.md
   - getting_started.md
   - addon_UI.md
   - other_panels.md
   - merge_visible.md
   - change_log.md
   - final_note.md
theme: readthedocs
use_directory_urls: false